# frozen_string_literal: true

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/user_feedbacks', type: :request, skip: 'TBD' do
  # UserFeedback. As you add validations to UserFeedback, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      UserFeedback.create! valid_attributes
      get user_feedbacks_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      user_feedback = UserFeedback.create! valid_attributes
      get user_feedback_url(user_feedback)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_user_feedback_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      user_feedback = UserFeedback.create! valid_attributes
      get edit_user_feedback_url(user_feedback)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new UserFeedback' do
        expect do
          post user_feedbacks_url, params: { user_feedback: valid_attributes }
        end.to change(UserFeedback, :count).by(1)
      end

      it 'redirects to the created user_feedback' do
        post user_feedbacks_url, params: { user_feedback: valid_attributes }
        expect(response).to redirect_to(user_feedback_url(UserFeedback.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new UserFeedback' do
        expect do
          post user_feedbacks_url, params: { user_feedback: invalid_attributes }
        end.to change(UserFeedback, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post user_feedbacks_url, params: { user_feedback: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested user_feedback' do
        user_feedback = UserFeedback.create! valid_attributes
        patch user_feedback_url(user_feedback), params: { user_feedback: new_attributes }
        user_feedback.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the user_feedback' do
        user_feedback = UserFeedback.create! valid_attributes
        patch user_feedback_url(user_feedback), params: { user_feedback: new_attributes }
        user_feedback.reload
        expect(response).to redirect_to(user_feedback_url(user_feedback))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        user_feedback = UserFeedback.create! valid_attributes
        patch user_feedback_url(user_feedback), params: { user_feedback: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested user_feedback' do
      user_feedback = UserFeedback.create! valid_attributes
      expect do
        delete user_feedback_url(user_feedback)
      end.to change(UserFeedback, :count).by(-1)
    end

    it 'redirects to the user_feedbacks list' do
      user_feedback = UserFeedback.create! valid_attributes
      delete user_feedback_url(user_feedback)
      expect(response).to redirect_to(user_feedbacks_url)
    end
  end
end
