name: Rails Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 2.6.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5

      - name: Install App
        env:
          RAILS_ENV: test
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bin/rake db:setup dad_tasks:update_database dad_tasks:init_site_status dad_tasks:update_patch_notes RAILS_ENV=test

      - name: Run Tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432
        run: |
          bin/rails test

      - name: Run Spec Tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432
        run: |
          bin/bundle exec rspec spec/